//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbaraDoces.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Novidade
    {
        public int Id_Novidade { get; set; }
        public string Desc_Novidade { get; set; }
        public string Titulo_Novidade { get; set; }
        public System.DateTime Dt_Novidade { get; set; }
        public int Id_Produto { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
