//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbaraDoces.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.Novidade = new HashSet<Novidade>();
            this.TipoProdutoXProdutoXSaborXPreco = new HashSet<TipoProdutoXProdutoXSaborXPreco>();
        }
    
        public int Id_Produto { get; set; }
        public string Nome_Produto { get; set; }
        public string Desc_Produto { get; set; }
        public string Vali_Produto { get; set; }
        public bool Ativo { get; set; }
        public byte[] Imagem_Produto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Novidade> Novidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoProdutoXProdutoXSaborXPreco> TipoProdutoXProdutoXSaborXPreco { get; set; }
    }
}
