//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbaraDoces.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProdutoXProdutoXSaborXPreco
    {
        public int Id_TipoProdutoXPreco { get; set; }
        public int Id_TipoProduto { get; set; }
        public int Id_Produto { get; set; }
        public int Id_Sabor { get; set; }
        public int Id_Preco { get; set; }
    
        public virtual Preco Preco { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Sabor Sabor { get; set; }
        public virtual TipoProduto TipoProduto { get; set; }
    }
}
